### ISSUE TITLE
update

### ISSUE THREAD

**Issue by paulsavo1** [claudioruiz/calendario-copa-america-2019#1]
Hi does this auto update, QF games not showing all teams yet

**Comment by claudiorrrr** [comment]
Fixed https://github.com/claudioruiz/calendario-copa-america-2019/commit/2cb7cd3ab6838c82d16416e8ceaacc15eb31995a 

It should be updated automatically

**Comment by paulsavo1** [comment]
no mate it just says for eg Colombia v 2C

its no big deal just be nice if gave full fixtures

**Comment by claudiorrrr** [comment]
Did you try to refresh it? I just checked and it seems updated (including the flags!)
Remember to "subscribe" instead of downloading the file and uploading to your calendar (in that case, of course it will not be automatically updated)
